partials:
  - name: about_me
    title: 'AboutMe'
    avatar: 'me.jpg'  # = /static/upload/me.jpg
    intro: '你看到了我哟'
    sns:
    - twitter: 'example'
    - github: 'example'
    - douban: 'example'
    - linkedin: 'example'
    - instagram: 'example'
    - stack-overflow: 'example'
    - medium: 'example'
    - zhihu: 'example'
    - email: 'example'
    - wechat: 'wechat-qrcode.jpg'
    - weixingongzhonghao: 'wechat-subscription-account-qrcode.png'
