[tool.black]
line-length = 88
py38 = true
skip-string-normalization = true

[tool.isort]
known_third_party = "sanic"
not_skip = "__init__.py"
multi_line_output = 5
include_trailing_comma = true
force_grid_wrap = 0
force_single_line = false
balanced_wrapping = true
use_parentheses = true